FROM paddleocr-model:local

WORKDIR /workspace

# Clone PaddleOCR pendant le build
RUN git clone https://github.com/PaddlePaddle/PaddleOCR.git

COPY OCR/PADDLE_TRAINING/script/export_ppocr_model.sh /workspace/script/export_ppocr_model.sh

# Patch pour désactiver l'assertion problématique
RUN sed -i '/assert (/,+3 s/^/#/' PaddleOCR/ppocr/utils/export_model.py

ENTRYPOINT ["bash", "/workspace/script/export_ppocr_model.sh"]