services:
  sync:
    image: alpine:3.20
    volumes:
      - ocrdata:/workspace/data
      - type: bind
        source: ${HOST_DATA_DIR}
        target: /host
    command: >
      sh -c "apk add --no-cache rsync &&
            rsync -av --delete --exclude 'crops/' /host/ /workspace/data/ &&
            echo '[sync] done' &&
            ls -l /workspace/data | head -n 20"
        restart: "no"

  train:
    image: paddleocr-train:local
    working_dir: /workspace
    depends_on:
      sync:
        condition: service_completed_successfully
    # lance le script CTC dans le conteneur
    entrypoint: ["bash","-lc","/workspace/script/launch_ocr_train.sh /workspace/data"]
    environment:
      - DICT=/workspace/dict/latin_dict.txt
      - RESUME=0             # mets 1 pour reprendre ./output/latin_ppocrv3/latest
      - FLAGS_use_shared_memory=0
    gpus: all
    shm_size: "1g"
    volumes:
      - ocrdata:/workspace/data
      - type: bind
        source: ./OCR/PADDLE_TRAINING/script
        target: /workspace/script
      - type: bind
        source: ./OCR/PADDLE_TRAINING/dict
        target: /workspace/dict
        read_only: false
      - type: bind
        source: ./OCR/PADDLE_TRAINING/config
        target: /workspace/config
      - type: bind
        source: ./OCR/PADDLE_TRAINING/pretrain_models
        target: /workspace/pretrain_models

volumes:
  ocrdata:
