# Dockerfile_paddle_ocr
FROM paddlepaddle/paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Dépendances minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
      git ca-certificates curl tar && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir "numpy<2.0" "imgaug<0.4.0"

# Code PaddleOCR
WORKDIR /opt
ARG PADDLEOCR_REF=release/2.7
RUN git clone --depth 1 --branch ${PADDLEOCR_REF} https://github.com/PaddlePaddle/PaddleOCR.git
WORKDIR /opt/PaddleOCR
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -U pip "numpy<2" && pip3 install -r requirements.txt

# Point par défaut
WORKDIR /opt/PaddleOCR
CMD ["/bin/bash"]
