services:
  sync:
    image: alpine:3.20
    volumes:
      - ocrdata:/workspace/data          # <—
      - type: bind
        source: ${HOST_DATA_DIR}         # dossier source côté hôte
        target: /host
    command: >
      sh -c "apk add --no-cache rsync &&
             if [ ! -d /host ] || [ -z \"$(ls -A /host)\" ]; then
               echo '[sync] /host vide ou introuvable' >&2; exit 2; fi &&
             rsync -av --delete /host/ /workspace/data/ &&
             echo '[sync] done' &&
             ls -l /workspace/data | head -n 20"
    restart: "no"

  train:
    image: paddleocr-train:stable
    gpus: all
    working_dir: /workspace
    command: ["bash","-lc","sleep infinity"]   # <-- garde le conteneur en vie
    volumes:
      - type: bind
        source: C:\Users\damien_dous\dev\DB\currentFolder   # <-- tes JSON + images (img_FULL, etc.)
        target: /workspace/data
      - type: bind
        source: C:\Users\damien_dous\dev\dict               # <-- doit contenir latin_dict.txt
        target: /workspace/dict
        read_only: true
      - type: bind
        source: C:\Users\damien_dous\dev\en_PP-OCRv3_rec.multihead.yml  # <-- ta config MultiHead
        target: /workspace/config/en_PP-OCRv3_rec.multihead.yml
        read_only: true

volumes:
  ocrdata:
