# Dockerfile_paddle_ocr
FROM paddlepaddle/paddle:2.6.1-gpu-cuda11.2-cudnn8.2-trt8.0

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

# Dépendances minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
      git ca-certificates curl tar && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir "numpy<2.0" "imgaug<0.4.0"

# Code PaddleOCR
WORKDIR /opt
ARG PADDLEOCR_REF=release/2.7
RUN git clone https://github.com/PaddlePaddle/PaddleOCR.git && \
    cd PaddleOCR && \
    git checkout ${PADDLEOCR_REF}
ENV PYTHONPATH=/opt/PaddleOCR:$PYTHONPATH
WORKDIR /opt/PaddleOCR
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -U pip "numpy<2" && pip3 install -r requirements.txt

# Point par défaut
WORKDIR /opt/PaddleOCR
CMD ["/bin/bash"]
