Global:
  debug: false
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/rec_ppocr_v3_latin
  save_epoch_step: 3
  eval_batch_step:
  - 0
  - 2000
  cal_metric_during_train: true
  pretrained_model: /workspace/pretrain_models/latin_PP-OCRv3_rec_train/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: /workspace/dict/latin_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3.txt
  global_batch_size: 512
  use_visualdl: true
  load_static_weights: true
  
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride:
    - 1
    - 2
    last_pool_type: avg
  Head:
    name: CTCHead
    Neck:
      name: svtr
      dims: 64
      depth: 2
      hidden_dims: 120
      use_guide: true
    Head:
      fc_decay: 1.0e-05

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  keep_space: false

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace
    label_file_list:
    - /workspace/output/train.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug: null
    - CTCLabelEncode: null
    - SVTRRecResizeImg:
        image_shape: [3, 32, 640]
        width_downsample_ratio: 0.25
        mode: v3
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 256
    drop_last: true
    num_workers: 8
    use_shared_memory: True

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /workspace
    label_file_list:
    - /workspace/output/val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - SVTRRecResizeImg:
        image_shape: [3, 32, 640]
        width_downsample_ratio: 0.25
        mode: v3
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4

profiler_options: null
